# Generated by Django 3.2.8 on 2021-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('max_passenger', models.PositiveIntegerField(default=1)),
                ('manufacture_year', models.PositiveIntegerField(default=2021)),
                ('manufacturer', models.CharField(max_length=250)),
                ('model', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First_Class', 'First_Class)')], max_length=12)),
                ('motor', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Electric_Motor', 'Electric_Motor')], max_length=15)),
            ],
        ),
    ]
