# Generated by Django 3.2.8 on 2021-12-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='model',
            new_name='model_type',
        ),
    ]
