# Generated by Django 3.2.8 on 2021-12-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_auto_20211221_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_motor',
        ),
    ]
