# Generated by Django 3.2.8 on 2021-12-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0003_remove_car_car_motor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarMotor',
        ),
        migrations.AddField(
            model_name='car',
            name='car_motor',
            field=models.CharField(choices=[('Hybrid', 'Hybrid'), ('Electric_Motor', 'Electric_Motor')], default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_category',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First_Class', 'First_Class)')], max_length=12),
        ),
        migrations.DeleteModel(
            name='CarCategory',
        ),
    ]
